[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Control"

[selection]
save_to_clipboard = true

[window]
opacity = 0.98
title = "Alacritty-Record"

[window.class]
general = "Alacritty"
instance = "Alacritty-Record"
