#!/bin/bash
mkdir -p ${HOME}/.cache/xmonad/build-x86_64-linux
/usr/bin/ghc --make xmonad.hs -i -ilib -fforce-recomp -main-is main -dynamic -v0 -outputdir ${HOME}/.cache/xmonad/build-x86_64-linux -o ${HOME}/.cache/xmonad/xmonad-x86_64-linux
